### ISSUE TITLE
Updates to OncoKB 

### ISSUE THREAD

**Issue by zhx828** [KarchinLab/open-cravat#108]
Hi team, thanks again for including OncoKB on this great tool! I'm trying to validate some of the annotation to see whether they are properly annotated. Could you help make the following changes? I'd also happy to maintain this tool if you think that's better going forward.

- [ ] No need to include evidenceTypes when making API call to OncoKB
- [ ] `referenceGenome` should not be set to 38, but rather depends on what user's genome Selection
- [ ] Do not show OncoKB under the Annotations when user selects hg18/GRCh36. We only support 37 and 38.
- [ ] In the Variant tab, under the OncoKB section, could you show Therapeutic before Diagnostic?
- [ ] In the Therapeutic, do no show Approved Indications
- [ ] In the Therapeutic, not sure why the Level shows 0 only even the drug is Level 1
- [ ] In the Therapeutic, the cancer name is empty

Thank you in advance.

**Comment by mlarsen2** [comment]
Hi Hongxin,
 
Thank you so much for using OpenCravat and we are so happy we can include OncoKB! After reading through your requested changes, the following updates have been made to the oncokb annotator in version 1.1.3 and the corresponding widget wgoncokb version 1.0.2.
 
I wanted to first address your suggestions about the reference genome and the different genome options for the OncoKB annotator. OpenCravat users can always choose what genome to run their job in, but it is always converted to hg38 coordinates and that's why the referenceGenome is set to hg38. If the user would like to run the job in hg37, their coordinates will be converted to hg38 prior to the API call, and the hg37 coordinates can still be viewed under the Original Input section of the variant table. 
 
1. The evidenceTypes were removed from the API call in the annotator.
2. The Therapeutic tab has been moved before the Diagnostic tab in the widget.
3. There is no longer an Approved Indications column in the Therapeutic tab.
4. For the "Level" issue in the Therapeutic tab, we have changed the "level" entry to the first "level" field under "treatments", previously we were displaying the "level" under "levelAssociatedCancerType".
5. We were displaying the name under "levelAssociatedCancerType", which in some instances is empty. When this cancer name is empty, we will display the "name" under "mainType" within "levelAssociatedCancerType" instead. Is this an acceptable solution ?

Please let me know your thoughts and if these changes are acceptable.
