### ISSUE TITLE
Job hung at "running gene mapper..."

### ISSUE THREAD

**Issue by CypherAce** [KarchinLab/open-cravat#119]
As the title describes, I'm having an issue that I'm at a loss to diagnose. I have completely nuked and reinstalled my installation of open-cravat on this linux system twice at this point. When I try to run any job, it simply hangs and never gets past the "running gene mapper..." step of the process. I know the files in question are fine because I was able to run them on a brand new windows installation I setup as a test. I just don't know what the issue is at this point.

**Comment by CypherAce** [comment]
I'll add, for the sake of thoroughness, that the hang also occurs in example input I generate with OC itself and I have checked and the hg38 mapper is installed.

**Comment by kmoad** [comment]
Could you send the output of `oc config cravat` and `oc config system`. Also, the log files for the job. They should be something like `INPUTFILENAME.log`.

Also, you could try nuking and re-installing the mapper module

```
oc module uninstall hg38
oc module install hg38
```

**Comment by skoul9** [comment]
I am facing a similar issue.

I installed Open Cravat on my workspace in a cluster environment and on my local machine (Mac OS) using pip. I can run the example-input on my local machine, but on the cluster, the program hangs at the mapper step, and an error is reported saying that a new thread can not be started. I raised the RAM and number of cores to ensure it is not due to a computing resource limitation, but I need help getting past that step. Can I modify environment settings or OC options to make it work?

I don't know if this is an error related to the mapper or if it coincides with the mapping step.

`Exception in thread Thread-1:
Traceback (most recent call last):
  File ".../python/3.9.10/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File ".../python/3.9.10/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File ".../python/3.9.10/lib/python3.9/multiprocessing/managers.py", line 194, in accepter
    t.start()
  File ".../python/3.9.10/lib/python3.9/threading.py", line 892, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread`

Please note that I have deleted some portions in the path of threading.py.

**Comment by skoul9** [comment]
Adding the "mp" parameter suppressed the error.
