### ISSUE TITLE
vcf-converter error

### ISSUE THREAD

**Issue by 2007lab** [KarchinLab/open-cravat#136]
Log file shows these errors
2023/02/09 10:04:09 cravat.converter liftover from hg19
2023/02/09 10:04:11 cravat.converter input format: vcf
2023/02/09 10:04:12 cravat.converter Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/cravat/cravat_convert.py", line 523, in run
converter.addl_operation_for_unique_variant(
File "/usr/local/lib/python3.10/dist-packages/cravat/modules/converters/vcf-converter/vcf-converter.py", line 347, in addl_operation_for_unique_variant
oc_val = ','.join(map(tmp, info_val))
TypeError: 'bool' object is not iterable
2023/02/09 10:04:33 cravat.converter error lines: 93
2023/02/09 10:04:33 cravat.converter finished: Thu Feb 9 10:04:33 2023
2023/02/09 10:04:33 cravat.converter num input lines: 407
2023/02/09 10:04:33 cravat.converter runtime: 22.518
2023/02/09 10:04:33 cravat num_workers: 11
2023/02/09 10:04:34 cravat input line chunksize=37 total number of input lines=407 number of chunks=11

**Comment by kmoad** [comment]
This is likely an issue with the VCF headers. Issues like this can occur if a VCF header mislabels a value type as per-allele instead of per-variant.

If you're able to share the vcf, we might be able to find the offending line. Please email it to support@opencravat.org if you're not comfortable sharing it here.
