### ISSUE TITLE
Questions re Original Cravat vs Open Cravat

### ISSUE THREAD

**Issue by MarkWaltham** [KarchinLab/open-cravat#140]
Hi, I use both earlier version of cravat and open cravat (and love them both!)
a) Id like to know if there is any way to tell what release of gnomad and ESP6500 is being used when I request that using Original cravat? I can see the release being used when using Open Cravat (great!).
b) Also the information that spits out (for gnomad and ESP6500) seems to be very different for Original Cravat vs Open Cravat.  Is there a reason im seeing that? Are the same simple AF that are reported in Original Cravat also there within Open Cravat?
Many thanks, Mark Waltham, PhD, Melbourne Australia.

**Comment by kmoad** [comment]
The data on cravat.us is pretty old. GnomAD and ESP6500 would be versions from prior to 2018. For gnomAD this means version 2 instead of 3. Which explains the difference in the data.

If by simple AF you mean the gnomAD global AF, then yes that is in OpenCRAVAT.

Let us know if this answers your question.

**Comment by MarkWaltham** [comment]
Hi Kyle. Yes that helps answer my questions. Thanks for looking into it!  Mark.
