### ISSUE TITLE
some annotators from the store fail to annotate chrM variants

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#148]
Hi, 

I've noticed that some annotators from the store (for example clinvar and omim, but I suspect that the problem is bigger) fail to annotate variants from chrM (even though these variants are present in the sqlite file). You can test it on the rs2001031 for example. 

The fix for this is the correct `setup()` function and declaration of `self.supported_chroms` but these are absent from majority of annotators. 

Really looking forward for the massive fix, otherwise it will be really painful to manually perform all fixes in the stock annotators.   

Best, Eugene

**Comment by kmoad** [comment]
I've committed a fix for this for clinvar and omim. https://github.com/KarchinLab/open-cravat-modules-karchinlab/commit/03ea9e566f5da7b6dc1ed8dbbae8f994b5dd27f5

Not able to push the fix until next week due to datacenter downtime (see https://github.com/KarchinLab/open-cravat/issues/151). I'll update this issue when the fix is out.

We'll have to go through the other annotators and make sure chrM support is in place. 

These annotators already have support.

- ensembl_regulatory_build
- fathmm
- gerp
- mitomap
- ncer
- phastcons
- phdnspg
- phylop
- segway

**Comment by EugeneEA** [comment]
@kmoad  Thanks a lot for the fast response! 
Best, Eugene
