### ISSUE TITLE
Summary panel widgets not loading

### ISSUE THREAD

**Issue by RachelKarchin** [KarchinLab/open-cravat#182]
![image](https://github.com/KarchinLab/open-cravat/assets/12953556/1c412e97-c059-4e22-bda7-6a0823be7635)
![image](https://github.com/KarchinLab/open-cravat/assets/12953556/ae4891a3-65a5-4a1c-8ad1-f708872fe5aa)
![image](https://github.com/KarchinLab/open-cravat/assets/12953556/7b4c8a19-a2ee-4d43-8ce0-8322bc114ae6)

**Comment by kmoad** [comment]
This has been fixed in https://github.com/KarchinLab/open-cravat/commit/a7c6e65e06f4dd0572b278b1317a6cbe099c9558 and https://github.com/KarchinLab/open-cravat-modules-karchinlab/commit/03bb2b781c927d1850a49dc19386469d599d0fc3 .

The fix is available on run.opencravat.org. Local users should upgrade to release 2.4.2 and update their modules.
