### ISSUE TITLE
scipy is not installed as a requiremnt

### ISSUE THREAD

**Issue by cvaske** [KarchinLab/open-cravat#272]
**Describe the bug**
Run ends with error due to a missing scipy import. I'm running a WGS trio from Illumina DRAGEN pipeline through Cravat with ClinVar, case-control, and SpliceAI modules. 

**To Reproduce**
In the GUI:
1. Upload three VCF files.
2. Select "ClinVar", "SpliceAI", "Gene Ontology" as modules
3. Upload a case-control cohort in the "Additional Analysis" section.
4. Start the Annotation

**Expected behavior**
A completed run.

**Desktop (please complete the following information):**

Run on macOS, using pyenv for a virtual environment based on Python 3.12.1, with no pip installed packages other than `open-cravat`

**Additional context**
I've attached the run log, and the `pip freeze` output.
* [log.txt](https://github.com/user-attachments/files/15920668/log.txt)
* [pip-freeze-2024-06-20-missing-scipy.txt](https://github.com/user-attachments/files/15920672/pip-freeze-2024-06-20-missing-scipy.txt)

**Comment by RachelKarchin** [comment]
Hi Charlie! Sorry for the delayed response. We have the scipy installation requirement in our documentation, but per your suggestion we will automate this so that anyone installing the Case-Control Summary module gets a scipy installation if it is not already installed on their machine. This has been added to our job queue and will be out with our next release.
