### ISSUE TITLE
Annotation confusion

### ISSUE THREAD

**Issue by cheanney** [KarchinLab/open-cravat#280]
Hi, 

First of all, we want to thank you for this wonderful application. It has streamlined our variant annotation workflow tremendously.

We submitted the HG19 chr16-11349332-CC-TT variant to OpenCravat and received the following results:

cDNA change: c.3_4delinsAA
**Protein change: p.Val2_Met119del**
As you can see, the cDNA change does not match the protein change p.Val2_Met119del.  Not sure why this variant which is in the initiator methionine is being called a large deletion Val2_Met119del. **It is only a 2-nucleotide deletion.**

<img width="992" alt="Screenshot 2024-07-30 at 10 55 52 AM" src="https://github.com/user-attachments/assets/3dd21226-fc97-40bf-80f3-afb4d621454a">

Then, we submitted this variant to VEP and VarSome, and the results were:

cDNA change: c.3_4delGGinsAA
**Protein change: p.(Met1_Val2delinsIleIle)**
[VarSome Result](https://varsome.com/variant/hg19/SOCS1(ENST00000332029.2):c.3_4delGGinsAA?&annotation-mode=germline)
<img width="1489" alt="Screenshot 2024-07-30 at 12 35 43 PM" src="https://github.com/user-attachments/assets/d843c39a-a4c8-4eb4-b3e7-50c21012da28">

Here are the cDNA and protein locations from vep:

<img width="1366" alt="Screenshot 2024-07-30 at 12 38 20 PM" src="https://github.com/user-attachments/assets/5372ef95-9809-4100-887c-6bb205f149ad">

Let me know if we can provide additional information.

Best, 

Anney

**Comment by jasminebro** [comment]
Hi, we will take a look at this issue! Thank you for the information.

**Comment by cheanney** [comment]
Hi Open-Cravat team, 

First, we want to express our gratitude for this fantastic tool. Open-Cravat is a vital component of our annotation workflow. That said, we would like to ask if you have had the chance to look into this issue.

Thanks,

Anney

**Comment by kmoad** [comment]
Hi cheanney,

Apologies for the delay on our end for looking into this.

Our opinion is that the call of Val2_Met119del is correct. chr16-11349332-CC-TT results in a start loss by changing the (reverse strand) sequence from `ATGGTA` to `ATAATA`. The next start codon is at position 119.

[HGVS recommendations](https://hgvs-nomenclature.org/stable/recommendations/protein/extension/) are that, "variants affecting the translation initiation site (Met1), activating an upstream (N-terminal) translation initiation site, are described as [deletion-insertion](https://hgvs-nomenclature.org/stable/recommendations/protein/delins/); **those activating a downstream (C-terminal) initiation site as a [deletion](https://hgvs-nomenclature.org/stable/recommendations/protein/deletion/)**."

[Here is the site of the variant](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr16%3A11349329%2D11349343&hgsid=2398396659_eLpnwAfwXZvNGeswKrUyomq5a5iA), and [here is the site of the predicted new start codon](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr16%3A11348963%2D11349007&hgsid=2398396659_eLpnwAfwXZvNGeswKrUyomq5a5iA).

We think that the VarSome call is incomplete because, while the new sequence `ATAATA` would translate to `IleIle`, it's important to annotate that the translation start is lost.

We're very interested in what you think about our observations. Please let us know if you see something wrong with our reasoning in this case. We really appreciate you bringing this to our attention (this was fun to chase down).
