### ISSUE TITLE
Error while annotating multi sample VCF

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#39]
Hi!

I am trying to annotate a population vcf file (75 samples) but I am getting an error. You can access the vcf file and the log in the link bellow:

https://drive.google.com/drive/folders/1jjwGNmujaNm8Wx9iaoeUIlTk7UsGQTM6?usp=sharing

Thanks for your support!

**Comment by rkiminsilico** [comment]
Hi, thanks for letting us know. some variants were not properly handled by the hg38 mapper. I'll take a look. Regarding the error with clinvar, can you check with `oc module install clinvar` ? It may be that the data for the clinvar module is not properly installed. Regarding the last exception, it will be fixed in the next release (open-cravat 2.1.3), but if you prefer you can patch yourself for now: do `pip list -v | grep cravat` to know the location of the site-packages folder for your Python. Then, that folder/cravat/inout.py should be replaced with the file of the same name at https://github.com/KarchinLab/open-cravat/blob/2.1.3/cravat/inout.py.

**Comment by kokyriakidis** [comment]
Q1: Can I use an already annotated VCF (e.g. EXAC, Clinvar) file with openCravat? 

Q2:
```
kokyriakidis@XAROS-WORKSTATION:~/Desktop$ oc module install clinvar
clinvar: latest is already installed. (2020.02.11.1)
No modules to install found
```

**Comment by rkiminsilico** [comment]
Yes, you can use already annotated VCF. The annotation fields in the INFO column will be transferred to the result of `oc run`, under "Extra VCF Info" group.

Regarging clinvar, can you show me the result of `oc module ls clinvar` ? The size of the module should be 115.3MB. If not, `oc module install clinvar -f -d` will force re-installing the module.

**Comment by kokyriakidis** [comment]
kokyriakidis@XAROS-WORKSTATION:/media/kokyriakidis/PRODUCTION/ADHD/work$ oc module ls clinvar
Name       Title      Type         Version         Data source ver    Size        
clinvar    ClinVar    annotator    2020.02.11.1    2020.02.11         115.3 MB

**Comment by kokyriakidis** [comment]
I reinstalled it but no change
[log3.txt](https://github.com/KarchinLab/open-cravat/files/5461194/log3.txt)

**Comment by rkiminsilico** [comment]
Thanks. I'm testing on my system now. I'll get back to you after the test.

**Comment by kokyriakidis** [comment]
Here is a log using many annotators. Many tracebacks occure
[Uploading log4.txt…]()

**Comment by rkiminsilico** [comment]
Can you share the .err file also? On my system, clinvar went fine and .err file can reveal more about what happened.

**Comment by kokyriakidis** [comment]
[ADHD-gatk-haplotype-annotated.vcf.zip](https://github.com/KarchinLab/open-cravat/files/5465555/ADHD-gatk-haplotype-annotated.vcf.zip)

**Comment by rkiminsilico** [comment]
Thanks. The errors from the annotation modules (clinvar, metasvm, and etc) were because their data does not cover the alternate chromosomes. We try to faithfully transfer original annotation data, so most likely the source data does not have these alternate chromosomes, but we will take a look again. The errors from the mapper are mostly fixed. I'll publish a new mapper for you to use soon.

**Comment by kokyriakidis** [comment]
Thank you so much for your support!

I will wait!

**Comment by rkiminsilico** [comment]
The fixed version of mavedb (1.0.1), metalr (1.0.2), and swissprot_ptm (1.0.1) have been published. With these, I think that the only remaining issue is the one related to alternate chromosomes. We'll check and get back to you.

**Comment by rkiminsilico** [comment]
We have just verified that the source data of those annotation modules does not have the alternate chromosomes which produced exceptions in your job. The next version of open-cravat, 2.1.3, will handle it better so that something else than no such table exception will show on the log file.

I think that this concludes the investigation and fix, but is there any remaining issue?

**Comment by kokyriakidis** [comment]
No! Thank you very much for you quick response! Keep up the good work!
