### ISSUE TITLE
Potential problem in hg19 position annotator

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#63]
Hi, I've noticed some strange behavioure of Hg19 annotator. Shortly, I'm annotating the vcf file with -l hg19 option and get the correct results (oc correctly lifts position to hg38). But it also write new column, called hg19 with the position and, for indels, this position is different by 1 to what it was in origianl vcf file (please see the picture)
![image](https://user-images.githubusercontent.com/57629300/114718800-0823da80-9d3f-11eb-94d4-e44117569b73.png)

as you can see ioriginal position in vcf was 17313566, which turns to 17313567
It seems that both number could be jastified:
gnomad uses first one for this rsID https://gnomad.broadinstitute.org/variant/1-17313566-AG-A?dataset=gnomad_r2_1
while ncbi uses the second one https://www.ncbi.nlm.nih.gov/snp/rs765632065

I personally think that it make more sense to stick to coordinates, which was written in original vcf, because otherwise it cose a confusion. Was such behavioure implemented intentionally or it is a bug?

Best, Eugene

**Comment by cariaso** [comment]
I won't pretend to answer this confidently, as that depends on knowing details of open-cravat. I will say that section 5.1.1 of
https://samtools.github.io/hts-specs/VCFv4.1.pdf
will speak to this. Correct behavior is somewhat non-intuitive

**Comment by EugeneEA** [comment]
Hi, thanks for the answer - I do understand that the issue might be non-intuitive, but for me (IMHO) it seems that the correct thigh would be to copy to the column hg19 whatever written in the position field of input vcf. And not to increase complexity level ;)

**Comment by rkimoakbioinformatics** [comment]
OpenCRAVAT normalizes variants first and then does liftover. For example,
```
7 10000 AGT A,AGCT,GT
```
becomes
```
7 10000 AGT A
7 10000 AGT AGCT
7 10000 AGT GT
```
which are normalized to
```
7 10001 GT -
7 10002 - T
7 10000 A -
```
which are then subject to liftover. "Hg19" position column has the positions after the normalization and thus means the position in the hg19 coordinate for normalized reference and alternate bases. We were concerned about using less disk space.

A question would be the use cases of the hg19 position column. If finding variants with their original position in the input file is the purpose of using it, then direct transfer before normalization would make sense. To be more correct, keeping the original reference and alternate bases would be necessary, since something like `7 10000 - T` (pre-normalization position and normalized bases) would not make sense. 

@EugeneEA How about keeping original positions, reference alleles, and alternate alleles in "Hg19" group columns? This will work for finding input variants for vcf and non-vcf input files, while losing normalized variant representation in the original hg19 coordinate.

**Comment by EugeneEA** [comment]
@rkimoakbioinformatics Thank you for the quick explanation (as usuall!). I bileve that it would be usefull to keep a connection to original vcf file, but I see the problem more clear now. Also now I'm a bit confused conserning the data bases which are used in the the Cravat. As far as I understand now, each db also go through the same "normalisation procedure"?  ( in the exmple above Gnomad2 and ClinVar has diffrerent representation of same SNP ). How should I deal with it when I'm preparing my own annotator? It turns out that is I will take raw gnomad (for example) and pack it into the annotator it will miss most (if not all) of the indels due to the different representation.

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA If an annotator's source data has VCF-style variants, we usually normalize them before making the annotator's database. For example, the variant "1-17313566-AG-A" (in hg19) is stored as "1-16987072-Gdel" (in hg38) in OpenCRAVAT's gnomad module (gnomAD 2.1). 

OpenCRAVAT does normalization first and then the standardized variants are fed to annotators. OpenCRAVAT's methods to normalize variants are shown below (they are in cravat_convert.py):
```
    def standardize_pos_ref_alt(self, strand, pos, ref, alt):
        reflen = len(ref)
        altlen = len(alt)
        # Returns without change if same single nucleotide for ref and alt.
        if reflen == 1 and altlen == 1 and ref == alt:
            return pos, ref, alt 
        # Trimming from the start and then the end of the sequence
        # where the sequences overlap with the same nucleotides
        new_ref2, new_alt2, new_pos = self.trim_input(ref, alt, pos, strand)
        if new_ref2 == "" or new_ref2 == ".":
            new_ref2 = "-" 
        if new_alt2 == "" or new_alt2 == ".":
            new_alt2 = "-" 
        return new_pos, new_ref2, new_alt2

    def trim_input(self, ref, alt, pos, strand):
        pos = int(pos)
        reflen = len(ref)
        altlen = len(alt)
        minlen = min(reflen, altlen)
        new_ref = ref 
        new_alt = alt 
        new_pos = pos 
        for nt_pos in range(0, minlen):
            if ref[reflen - nt_pos - 1] == alt[altlen - nt_pos - 1]: 
                new_ref = ref[: reflen - nt_pos - 1]
                new_alt = alt[: altlen - nt_pos - 1]
            else:
                break
        new_ref_len = len(new_ref)
        new_alt_len = len(new_alt)
        minlen = min(new_ref_len, new_alt_len)
        new_ref2 = new_ref
        new_alt2 = new_alt
        for nt_pos in range(0, minlen):
            if new_ref[nt_pos] == new_alt[nt_pos]:
                if strand == "+":
                    new_pos += 1
                elif strand == "-":
                    new_pos -= 1
                new_ref2 = new_ref[nt_pos + 1 :]
                new_alt2 = new_alt[nt_pos + 1 :]
            else:
                new_ref2 = new_ref[nt_pos:]
                new_alt2 = new_alt[nt_pos:]
                break
        return new_ref2, new_alt2, new_pos
```
Maybe making these methods more accessible so that module developers can conveniently use them will help, but for now you can use these to make sure that your custom annotator's variant representation go along with what will come to the annotator from OpenCRAVAT.

**Comment by EugeneEA** [comment]
Thanks for the clarifications, I think the issue could be closed.
Best Eugene

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA Just wanted to let you know that, when VCF format input is used, there three columns which preserves original input position, reference allele, and alternate allele. They are "VCF Position", "VCF Ref Allele", and "VCF Alt Allele" under "Extra VCF INFO Annotations" colunm group. Their column names are extra_vcf_info__pos, extra_vcf_info__ref, and extra_vcf_info__alt.
