### ISSUE TITLE
Rdata report generation error

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#85]
Hi!

I get the following message when I try to generate Rdata in opencravat 2.2.6:
```
rdata report generation failed for 211126-225135

Check your system's wcravat.log for details.
```

This happens even in both run.opencravat.org and locally.

**Comment by rkimoakbioinformatics** [comment]
Hi, in run.opencravat.org, somehow that job does not exist. As you try the job and RData report generation locally, an error message must be in wcravat.log in `logs` folder, which you can find with `oc config system|grep log_dir`. Do you see any error message from rdatareporter.py, in the `wcravat.log`?

**Comment by kokyriakidis** [comment]
You can check this one in the run.opencravat.org:

```
rdata report generation failed for 211126-205215

Check your system's wcravat.log for details.
```
or `211126-205237` or `211126-205237` or `211126-205237`

**Comment by rkimoakbioinformatics** [comment]
@kokyriakidis The reason was that `pandas` and `pyreadr` pip packages, which are needed by the rdatareporter module, were not installed in the server. The latest oc 2.1.7 and rdatareporter 1.2.0 should attempt installing these required packages when `oc module install rdatareporter` is run. 

I have installed the packages in run.opencravat.org and rdatareporter seems to work. When using rdatareporter in your local system, please install the two packages and try.

Please let me know if this works for you.

**Comment by kokyriakidis** [comment]
Thanks a lot! It works now!
