### ISSUE TITLE
Error lines

### ISSUE THREAD

**Issue by anleopa** [KarchinLab/open-cravat#90]
Hi,

I am trying to verify why some variants from my VCF have not been annotated (they pass the filters and they are not the reference genotype). In the log file I only see "Error lines: 99" but I don't know exactly why these lines throw an error. Is there any way of getting more info about it?

Thanks

**Comment by rkimoakbioinformatics** [comment]
Hi @anleopa, are you using run.opencravat.org or a locally installed OpenCRAVAT?

**Comment by anleopa** [comment]
Hi @rkimoakbioinformatics, A locally installed OpenCRAVAT

**Comment by anleopa** [comment]
Yes! I see it... some of them correspond to "Liftover failure" in the annotator and "syntax error" in the aggregator. What could be causing the "leftover failure"?

**Comment by rkimoakbioinformatics** [comment]
Liftover failure is usually for the locations which do not have a mapping position in hg38. `Syntax error` in aggregator is strange. Can you copy and paste one example of `syntax error` one? (from `SOURCE:` to `ERROR:`)

**Comment by anleopa** [comment]
These are a some examples:

SOURCE:error.aggregator     
LINE:0
INPUT:1	948846	T	TA	0.41880342	0.41880342	049		p36.33	3	117	67,49,25,24	UPSTREAM(MODIFIER||||ISG15|mRNA|CODING|NM_005101|)			(NC_000001.10:g.948846_948847insA,NM_005101.3:c.-108_-107insA,)		.	36				OMIM:147571	0	117,0,49,0		HET	1.0E-25
ERROR:near "(": syntax error

SOURCE:error.aggregator     
LINE:20804
INPUT:20805	55846761	C	T	0.62857145	0.62857145	44		q12.2	2	70.0	26,1,43,1	INTRON(MODIFIER||||CES1|mRNA|CODING|NM_001025194|),INTRON(MODIFIER||||CES1|mRNA|CODING|NM_001025195|),INTRON(MODIFIER||||CES1|mRNA|CODING|NM_001266|)			(NC_000016.9:g.55846761C>T,,),(NC_000016.9:g.55846761C>T,NM_001025195.1:c.1086+54G>A,),(NC_000016.9:g.55846761C>T,,)		0	36				OMIM:114835	0			HET	1.0E-25
ERROR:near "(": syntax error

**Comment by anleopa** [comment]
In the case of liftover failures... for example, in this record the variant is located in chr1 pos 145558565 (GRCh37) C>G
This variant has GRCh38 coordinates: 145,876,516 as can be seen in https://www.ncbi.nlm.nih.gov/clinvar/?term=rs11801520  but the converter was not able to covert it.

SOURCE:error.converter      
LINE:1344
INPUT:chr1	145558565	rs11801520	C	G	108	PASS	AF=1.0;AF1=1.0;ALTCOUNT=123;CHR_INDEL_ARM=q21.1;Category=2;DP=123.0;DP4=1,0,6,117;EFF=INTRON(MODIFIER||||ANKRD35|mRNA|CODING|NM_001280799|),INTRON(MODIFIER||||ANKRD35|mRNA|CODING|NM_144698|),INTRON(MODIFIER||||NBPF10|mRNA|CODING|NM_001039703|),INTRON(MODIFIER||||NBPF10|mRNA|CODING|NM_001302371|),INTRON(MODIFIER||||NBPF19|mRNA|CODING|NM_001351365|),INTRON(MODIFIER||||NBPF20|mRNA|CODING|NM_001278267|);HGVS=(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,NM_144698.4:c.453+53C>G,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,);IsKnownVariant=0;MQ=36;SEL_PRIMARY_EFF=0;Zygosity=HOM;pValue=1.0E-108	GT:AF:DP:GQ:PL	1/1:1.0:123:99:0,0,255
ERROR:Liftover failure

**Comment by rkimoakbioinformatics** [comment]
Thanks for the examples. 

Regarding `syntax error`, there should be a traceback in .log file for the error. Can you copy and paste that portion of .log file? That will reveal which part of aggregator produced the error.

Regarding `Liftover failure`, it seems to be an interesting edge case. OpenCRAVAT uses Liftover (https://genome.ucsc.edu/cgi-bin/hgLiftOver) to convert genomic coordinates. Liftover has a strange mapping hole for that specific position. Using the official Liftover web tool, conversion of the positions around chr1:145558565 is as follows:

chr1:145558564 (hg19) is converted to chr1:145876517 (hg38).
chr1:145558565 (hg19) is deleted in hg38.
chr1:145558566 (hg19) is converted to chr1:145876515 (hg38).

It seems that chr1:145558565 (hg19) should be mapped to chr1:145876516 (hg38), but the current Liftover tool produces no mapping. I guess dbSNP fixed this issue by looking at the surrounding positions' conversion. I have just made a quick fix with this algorithm, which solves the error with chr1:145558565. Since OpenCRAVAT's next release may be a bit later, If you want to try the fix, you can try with `pip uninstall open-cravat` and then `pip install oxygenv-core`, which will install Oxygen V Core which has the same oc commands, is a fork of OpenCRAVAT, and has the Liftover fix.

**Comment by anleopa** [comment]
This is what I have found in the log file:

2022/01/26 11:14:07 cravat.aggregator    Traceback (most recent call last):
  File "C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\lib\site-packages\cravat\aggregator.py", line 154, in run
    self.cursor.execute(update_template, ins_vals)
sqlite3.OperationalError: near "(": syntax error

Thanks for the fix!

**Comment by anleopa** [comment]
I have also seen that some variants such as rs6558397, in the GRCh37 assembly have this expression NC_000008.10:g.144940081C>A and in the GRCh38 assembly change the ref and alt alleles... NC_000008.11:g.143857908A>C
In these cases the conversion also fails.

**Comment by anleopa** [comment]
I have also found that in some cases the ref and al alleles change between assemblies. For example, rs67270413 is G>A in GRCh37 and A>G in GRCh38. In this case, the converter also throws an error.

**Comment by rkimoakbioinformatics** [comment]
Thanks. Regarding the `syntax error`, the input lines which gave this error in your example do not seem to have proper syntax for a VCF data line. For example,

This data line in your example produced the syntax error:
```
1 948846 T TA 0.41880342 0.41880342 049 p36.33 3 117 67,49,25,24 UPSTREAM(MODIFIER||||ISG15|mRNA|CODING|NM_005101|) (NC_000001.10:g.948846_948847insA,NM_005101.3:c.-108_-107insA,) . 36 OMIM:147571 0 117,0,49,0 HET 1.0E-25
```
while this did not:
```
chr1 145558565 rs11801520 C G 108 PASS AF=1.0;AF1=1.0;ALTCOUNT=123;CHR_INDEL_ARM=q21.1;Category=2;DP=123.0;DP4=1,0,6,117;EFF=INTRON(MODIFIER||||ANKRD35|mRNA|CODING|NM_001280799|),INTRON(MODIFIER||||ANKRD35|mRNA|CODING|NM_144698|),INTRON(MODIFIER||||NBPF10|mRNA|CODING|NM_001039703|),INTRON(MODIFIER||||NBPF10|mRNA|CODING|NM_001302371|),INTRON(MODIFIER||||NBPF19|mRNA|CODING|NM_001351365|),INTRON(MODIFIER||||NBPF20|mRNA|CODING|NM_001278267|);HGVS=(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,NM_144698.4:c.453+53C>G,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,),(NC_000001.10:g.145558565C>G,,);IsKnownVariant=0;MQ=36;SEL_PRIMARY_EFF=0;Zygosity=HOM;pValue=1.0E-108 GT:AF:DP:GQ:PL 1/1:1.0:123:99:0,0,255
```
The one with the syntax error does not have `EFF=` and `HGVS=` in `INFO` field, which should exist. It seems that the `syntax error` was caused by incomplete data lines.

By the way, was the input file the output of a program/pipeline? Just so that we can know about it and improve OpenCRAVAT's support for diverse VCF format situations.

**Comment by anleopa** [comment]
Yes, you are right about the INFO fields... This is the output of a pipeline, but I don't have the details about the technology/software used... I can try to find out if you need it.

**Comment by rkimoakbioinformatics** [comment]
> I have also found that in some cases the ref and al alleles change between assemblies. For example, rs67270413 is G>A in GRCh37 and A>G in GRCh38. In this case, the converter also throws an error.

The error for rs67270413 was because of no mapping in hg38 by liftover for the snp's hg19 position. G>A to A>G is a different matter, which is a bit tricky problem. The reference base G in hg19 can be corrected to A in hg38 using the sequence of hg38. However, the alternate base cannot be corrected that way. One sure way to get the correct alternate base in hg38 for the snp would be to get it using the rsID as a key. OpenCRAVAT has `dbsnp-converter`, which will produce correct hg38 position, reference base, and alternate base as output with rsID as input. However, if hg19 position, ref, and alt were all OpenCRAVAT starts with, then picking the correct alternate base when the reference base is different between hg19 and hg38 for a position would not have a basis. We would welcome any suggestion if you have.

**Comment by rkimoakbioinformatics** [comment]
> Yes, you are right about the INFO fields... This is the output of a pipeline, but I don't have the details about the technology/software used... I can try to find out if you need it.

Yes, that would help OpenCRAVAT and we would appreciate it.

**Comment by anleopa** [comment]
> > I have also found that in some cases the ref and al alleles change between assemblies. For example, rs67270413 is G>A in GRCh37 and A>G in GRCh38. In this case, the converter also throws an error.
> 
> The error for rs67270413 was because of no mapping in hg38 by liftover for the snp's hg19 position. G>A to A>G is a different matter, which is a bit tricky problem. The reference base G in hg19 can be corrected to A in hg38 using the sequence of hg38. However, the alternate base cannot be corrected that way. One sure way to get the correct alternate base in hg38 for the snp would be to get it using the rsID as a key. OpenCRAVAT has `dbsnp-converter`, which will produce correct hg38 position, reference base, and alternate base as output with rsID as input. However, if hg19 position, ref, and alt were all OpenCRAVAT starts with, then picking the correct alternate base when the reference base is different between hg19 and hg38 for a position would not have a basis. We would welcome any suggestion if you have.

Conversion is always complicated... In cases like mine, when the provider sends hg19 files, the conversion always produces errors or missing information. The only solution I have found, being conservative, is to have the possibility of annotate the files using hg19 databases and without conversion. OpenCravat could offer this possibility, but the annotation modules should also provide the hg19 coordiantes, which is costly....

**Comment by anleopa** [comment]
> > Yes, you are right about the INFO fields... This is the output of a pipeline, but I don't have the details about the technology/software used... I can try to find out if you need it.
> 
> Yes, that would help OpenCRAVAT and we would appreciate it.

I will let you know as long as I receive the answer from the provider
