### ISSUE TITLE
separateannotation not working

### ISSUE THREAD

**Issue by jkobject** [KarchinLab/open-cravat#92]
Hi, 

I am running opencravat in VCF mode with multiple inputs with this command:
`oc run CDS-010xbm.vcf.gz CDS-00rz9N.vcf.gz --separate-sample -l hg38 -t vcf --mp 4 --module-option vcfreporter.type=separate -d out`

I am trying to annotate the two vcfs and get an output with the two separate vcfs. However even with the option `--separate-sample`, I keep getting a merged VCF.

Thank you for the great tool!

**Comment by rkimoakbioinformatics** [comment]
@jkobject Hi, just to make sure I understand your question clearly - do you mean annotating CDS-010xbm.vcf.gz and CDS-00rz9N.vcf.gz and getting output files CDS-010xbm.vcf.gz.vcf and CDS-00rz9N.vcf.gz.vcf?

**Comment by jkobject** [comment]
Hi!

Yes this is what I mean

**Comment by rkimoakbioinformatics** [comment]
@jkobject Multiple variants on the same location are delimited with `,` in a VCF format output. For example,

`chr1    145558565   rs11801520  C   G,A 108 PASS` will give

`OC_base__hugo=ANKRD35,ANKRD35;OC_base__transcript=ENST00000355594.9,ENST00000355594.9;OC_base__so=intron_variant,intron_variant;OC_base__cchange=c.453+53G>C,c.453+53G>T`

In other formats, usually they are separated into multiple lines, one line per variant.

Somehow `vcfreporter` 3.1.0 had the bug of writing something like `OC_base__coding=chr1;OC_base__hugo=1000000` with wrong mismatch between field names and field values. `vcfreporter` 3.2.0 fixes the problem so that something like `OC_base__coding=Yes;OC_base__hugo=BRAF` will be correctly written.

The latest source code for the modules are maintained at https://github.com/rkimoakbioinformatics/oxygenv-modules-oakbioinformatics.

**Comment by jkobject** [comment]
Thank you very much!
